name: Run Bol.com Stock Checker (single run)

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  run-once:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies (for headless browser)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            libnss3 libxss1 libatk1.0-0 \
            libatk-bridge2.0-0 libcups2 libgbm1 libgtk-3-0

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bol.com stock checker once
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RUN_ONCE: "true"
        run: |
          python bolcom_pokemon_stock_checker.py
