name: Run Bol.com Stock Checker (single run)

# schedule is optional; keep workflow_dispatch so you can run manually
on:
  workflow_dispatch:
  # Uncomment to run on a schedule too:
  # schedule:
  #   - cron: '*/5 * * * *'   # every 5 minutes (public repo allowed)

jobs:
  run-once:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install apt dependencies for headless Chrome
        run: |
          sudo apt-get update
          # libraries commonly required by headless Chrome
          sudo apt-get install -y wget gnupg2 ca-certificates fonts-liberation libnss3 libxss1 libasound2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgbm1 libgtk-3-0
          # Install a Chromium package
          sudo apt-get install -y chromium-browser

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug: show python & chrome versions
        run: |
          python --version
          which chromium-browser || true
          chromium-browser --version || true

      - name: Run stock checker once
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RUN_ONCE: "true"
        run: |
          python bolcom_pokemon_stock_checker.py
